### ISSUE TITLE
New Feature: delay after filesystem event

### ISSUE THREAD

**Issue by tmueller** [Server4001/lr-server#2]
Hi,

thanks for creating lr-server. I'm using lr-server in an asp dotnet core environment. After changing a *.cs or *.cshtml file, the webserver is restarted and the browser should livereload. Unfortunately the livereload is triggered immediately, when the webserver is not finished restarting yet. 

Is it possible to add an option for a wait time, that delays the browser reload for x ms after the filesystem event was detected? The difference to the debounce options would be, that debounce only ignores subsequent filechanges, while the delay is always applied.

**Comment by Server4001** [comment]
@tmueller I think you might be describing `--interval`?

**Comment by Server4001** [comment]
@tmueller Yes, I will work on that.

**Comment by Server4001** [comment]
@tmueller v0.3.0:
`Use --reload-delay or -r to specify delay between file events and Livereload being called (default 0 milliseconds).`
